[package]
name = "watchmen"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = "0.12.22"
serde = { version = "1.0.219", features = ["derive"] }
surge-ping = "0.8.2"
tokio = { version = "1.21.2", features = ["full"] }
toml = "0.8.23"
